### ISSUE TITLE
Add FAQ on "No hyphenation patterns were preloaded"

### ISSUE THREAD

**Issue by koppor** [zauguin/install-texlive#13]
When "just" using the action to install packages, I get

```
Package babel Warning: No hyphenation patterns were preloaded for
(babel)                the language 'German (new orthography)' into the format.

(babel)                Please, configure your TeX system to add them and
(babel)                rebuild the format. Now I will use the patterns
(babel)                preloaded for \language=0 instead on input line 48.
```

Can there a) be FAQ added how to solve the issue or b) an automatism of the action be in place?

For MiKTeX, the solution seems to be https://tex.stackexchange.com/a/527651/9075, but IDK for TeXLive...

**Comment by zauguin** [comment]
This looks like you are just missing the hyphenation patterns. Can you add `hyphen-german` to your installed packages and see if the issue still appears?

**Comment by koppor** [comment]
Oh, wow, yeah, that works. 

I wonder, why `hyphen-german` does not appear at https://ctan.org/topic/hyphenation - and I also can't find it on CTAN - https://ctan.org/pkg/hyphen-german is 404. I mean, if it is contained in `dehyph`, shouldn't a request for `hyphen-german` lead to an error in TeXLive installer?

**Comment by koppor** [comment]
Maybe, n00bs should just google... - https://tex.stackexchange.com/q/365804/9075

**Comment by koppor** [comment]
Maybe you have an idea for

```
 pg 1: Package babel Warning: No hyphenation patterns were preloaded for
      (babel)                the language 'Ibycus' into the format.
      (babel)                Please, configure your TeX system to add them and
      (babel)                rebuild the format. Now I will use the patterns
      (babel)                preloaded for \language=0 instead on input line 35.
 pg 1: Package babel Warning: No hyphenation patterns were preloaded for
      (babel)                the language 'greek' into the format.
      (babel)                Please, configure your TeX system to add them and
      (babel)                rebuild the format. Now I will use the patterns
      (babel)                preloaded for \language=0 instead on input line 46.
```

`ibycus-babel` and `babel-greek` exist, [hyphenation-greek](https://ctan.org/pkg/hyphenation-greek) does not exist on TeXLive...

**Comment by arkonia** [comment]
Hi, you could try to use the [elhyphen](https://ctan.org/pkg/elhyphen)-package for greek.

**Comment by koppor** [comment]
@arkonia That was it. In TeXLive, it is even called `hyphen-greek`. Not that hard to guess 🤣. Thank you for your help!
