### ISSUE TITLE
tikz (and maybe other packages) not installed

### ISSUE THREAD

**Issue by arkonia** [zauguin/install-texlive#23]
Hello, I can not use `\usepackage{tikz}` because it's not installed. Adding `tikz` to the package list in the YAML file does not work also.

I do not know how to install a larger TeX distribution as basis. This would be good to get rid of other missing-package messages in the future.

**Comment by zauguin** [comment]
You need to use the texlive package name in package list, in this case that's `pgf`. The basis can be selected by adding one of the schemes to the package list. E.g. adding `scheme-full` installs everything, `scheme-small` a reasonable basis which can be extended when needed.

**Comment by arkonia** [comment]
Thanks a lot.
