### ISSUE TITLE
Add "packages" to cache key

### ISSUE THREAD

**Issue by koppor** [zauguin/install-texlive#3]
The caching key is very smart. Respecting daily TL updates. Nice.

I think, however, that besides `packages_file`, the explicit list of packages (`packages`) should be part of the key. That would enable "transparent" update of the explicit package list instead of having to use the cache version.

Location: https://github.com/zauguin/install-texlive/blob/b2ac644271ca4089f5960845b6465532dcaf19a4/action.yml#L37

I think, there are other locations, I could not quickly see it, but wanted to file the issue.

**Comment by zauguin** [comment]
Thanks for fixing this in #1.
