### ISSUE TITLE
Add texlive scheme

### ISSUE THREAD

**Issue by koppor** [zauguin/install-texlive#9]
Please add an argument `scheme` to select the [scheme](https://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-240003.2.2). Currently, `infrastructure-only` is selected. I would like to start with `basic`. Otherwise, at new projects, it takes me several hours to get the packages right (example: https://github.com/gi-ev/LNI/pull/124).

**Comment by zauguin** [comment]
Sorry for not answering sooner.

It shouldn't be needed to add an explicit `scheme` option since you can just add `scheme-basic` in the package list. This should then pull in the whole scheme. Since this just pulls in multiple packages, having it as part of the package list makes sense IMO.
